
@startuml

class A
{
    run_from_b()
}

class B
{
    run()
}

A  ---*  B


class A_specialized
{
    run_from_b()
}

class B_specialized
{
    run()
    other_specialized_method()
}

A_specialized  --|>  A
B_specialized  --|>  B

A_specialized  ---*  B_specialized
A_specialized  --->  B  : NONE

@enduml
