
@startuml

' ---------------------------------------------------------

package backend
{

interface BackendListener

interface Backend

Backend  ---o  "1"  BackendListener

}

' ---------------------------------------------------------
' ---------------------------------------------------------

package view
{

interface View

interface ViewListener

View  ---o  "1"  ViewListener


}

' ---------------------------------------------------------
' ---------------------------------------------------------

package controller
{

interface Controller

Controller  --|>  BackendListener
Controller  --|>  ViewListener

Controller  ---*  "1"  Backend
Controller  ---*  "1"  View

}

' ---------------------------------------------------------
' ---------------------------------------------------------

package specializes
{

class ViewPlotjuggler
class ViewPlotjugglerListener

ViewPlotjuggler  --|>  View
ViewPlotjugglerListener  --|>  ViewListener

class ControllerPlotjuggler

ControllerPlotjuggler  --|>  Controller
ControllerPlotjuggler  --|>  ViewPlotjugglerListener

}

' ---------------------------------------------------------

@enduml
